site_name: Pyprojectx

repo_url: https://github.com/pyprojectx/pyprojectx
edit_uri: edit/main/docs/docs
remote_name: https://github.com/pyprojectx/pyprojectx.github.io.git
remote_branch: main

theme:
  name: material
  features:
    - navigation.indexes
    - content.code.copy
    - navigation.top
    - navigation.instant
  palette:
    # Palette toggle for automatic mode
    - media: '(prefers-color-scheme)'
      primary: white
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: '(prefers-color-scheme: light)'
      primary: white
      scheme: default

      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: '(prefers-color-scheme: dark)'
      primary: white
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  logo: assets/px.svg
  favicon: assets/px.svg
  custom_dir: overrides

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: google

nav:
  - Home: index.md
  - Configuration:
    - config/tools.md
    - config/aliases.md
    - config/scripts.md
    - config/defaults.md
  - Usage: usage.md
  - Dev Dependencies: dev-dependencies.md
  - Recipes: recipes.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.snippets
  - admonition
  - tables
  - toc:
      permalink: "#"
  - markdown_include.include:
      base_path: docs

copyright: Copyright &copy; 2020 <a href="https://upcycled-code.com/">Ivo Houbrechts</a>

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pyprojectx/pyprojectx

extra_css: [assets/extra.css]
