name: Release

on:
  # Release is only done manually
  workflow_dispatch:
    branches:
      - main
    inputs:
      release_version:
        description: 'Which version to release'
        required: true

jobs:
  release-pypi:
    name: release-pypi
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Build release
        run: |
          ./pw prep-release ${{ inputs.release_version }}
          ./pw build
          git push origin ${{ inputs.release_version }}

      - name: Create github release
        uses: softprops/action-gh-release@v1
        with:
          body_path: .release-changelog.md
          files: wrappers.zip

      - name: Publish to Pypi
        run: ./pw publish --password ${{ secrets.PYPI_TOKEN }}
